version: "3.8"
services:
  indexicon:
    image: c854f2c5546c
    hostname: indexicon
    container_name: indexicon
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - "/home/user/.config/indexicon/addon:/usr/src/app/addon"
      - "/home/user/.config/indexicon/data:/usr/src/app/data"
      - "/home/user/Downloads/indexicon:/usr/src/app/download"
    restart: always
    environment:
      INDEXICON_DB_TYPE: "sqlite"
      INDEXICON_EXTENSIONS: ""